# Generated by Django 3.1.7 on 2021-04-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210405_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='location_name',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
