# Generated by Django 3.1.7 on 2021-04-11 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210410_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 22, 35, 8, 34806)),
        ),
    ]
