# Generated by Django 3.1.7 on 2021-04-11 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210410_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 0, 41, 53, 753105)),
        ),
    ]
