# Generated by Django 3.1.7 on 2021-04-12 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210411_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email_confirmation_due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 22, 5, 29, 681560)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 22, 5, 29, 681542)),
        ),
    ]
