# Generated by Django 3.1.7 on 2021-04-25 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210424_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email_confirmation_due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 21, 39, 46, 332566)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 21, 39, 46, 332549)),
        ),
    ]
