# Generated by Django 3.1.7 on 2021-04-30 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210428_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='has_submitted_trade_proposal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email_confirmation_due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 11, 36, 52, 451658)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 11, 36, 52, 451642)),
        ),
    ]
