# Generated by Django 3.1.7 on 2021-04-30 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210430_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='has_submitted_trade_proposal',
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_trade_proposal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email_confirmation_due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 13, 57, 16, 969392)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 13, 57, 16, 969374)),
        ),
    ]
