# Generated by Django 3.1.7 on 2021-04-30 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210430_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='conf_trade_opt_out_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email_confirmation_due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 16, 56, 5, 657549)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 16, 56, 5, 657532)),
        ),
    ]
