# Generated by Django 3.1.7 on 2021-05-20 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210507_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email_confirmation_due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 17, 56, 23, 973106)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 17, 56, 23, 973089)),
        ),
    ]
