# Generated by Django 3.1.7 on 2021-03-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_game'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='game',
            new_name='account',
        ),
    ]
