# Generated by Django 3.1.7 on 2021-03-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210314_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('platform', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='account',
        ),
    ]
