# Generated by Django 3.1.7 on 2021-03-14 22:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20210314_1945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_c',
            new_name='OwnedGame',
        ),
    ]
