# Generated by Django 3.1.7 on 2021-03-14 22:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210314_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesiredGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('owned_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ownedgame')),
            ],
        ),
    ]
