# Generated by Django 3.1.7 on 2021-03-14 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_desiredgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedgame',
            name='desired_game',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='blog.desiredgame'),
            preserve_default=False,
        ),
    ]
