# Generated by Django 3.1.7 on 2021-03-15 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_ownedgame_desired_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('platform', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_trade_proposed', models.BooleanField(default=False)),
                ('desired_game', models.ForeignKey(db_column='desired_game', on_delete=django.db.models.deletion.CASCADE, related_name='desired_game', to='blog.game')),
                ('owned_game', models.ForeignKey(db_column='owned_game', on_delete=django.db.models.deletion.CASCADE, related_name='owned_game', to='blog.game')),
                ('user_who_posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ownedgame',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ownedgame',
            name='desired_game',
        ),
        migrations.DeleteModel(
            name='DesiredGame',
        ),
        migrations.DeleteModel(
            name='OwnedGame',
        ),
    ]
