# Generated by Django 3.1.7 on 2021-03-15 03:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210315_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('trade_one', models.ForeignKey(db_column='trade_one', on_delete=django.db.models.deletion.CASCADE, related_name='trade_one', to='blog.game')),
                ('trade_two', models.ForeignKey(db_column='trade_two', on_delete=django.db.models.deletion.CASCADE, related_name='trade_two', to='blog.game')),
            ],
        ),
    ]
