# Generated by Django 3.1.7 on 2021-03-15 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='trade_one',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='trade_two',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
