# Generated by Django 3.1.7 on 2021-03-15 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_auto_20210315_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('trade_one', models.ForeignKey(db_column='trade_one', on_delete=django.db.models.deletion.CASCADE, related_name='trade_one', to='blog.game')),
                ('trade_two', models.ForeignKey(db_column='trade_two', on_delete=django.db.models.deletion.CASCADE, related_name='trade_two', to='blog.game')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_trade_proposed', models.BooleanField(default=False)),
                ('desired_game', models.ForeignKey(db_column='desired_game', on_delete=django.db.models.deletion.CASCADE, related_name='desired_game', to='blog.game')),
                ('owned_game', models.ForeignKey(db_column='owned_game', on_delete=django.db.models.deletion.CASCADE, related_name='owned_game', to='blog.game')),
                ('user_who_posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
