# Generated by Django 3.1.7 on 2021-04-25 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210424_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='condition',
            field=models.CharField(choices=[('Bad - A lot of scratches', 'Bad - A lot of scratches'), ('OK - 1 or 2 small scratches', 'OK - 1 or 2 small scratches'), ('Good - No scratches, 1 or 2 smudges', 'Good - No scratches, 1 or 2 smudges'), ('Perfect - No scratches, no smudges', 'Perfect - No scratches, no smudges')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 21, 39, 46, 312501)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='open_expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 21, 39, 46, 312519)),
        ),
    ]
