# Generated by Django 3.1.7 on 2021-03-15 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_trade_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trade_one',
            field=models.ForeignKey(db_column='trade_one', on_delete=django.db.models.deletion.CASCADE, related_name='trade_one', to='blog.trade'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trade_two',
            field=models.ForeignKey(db_column='trade_two', on_delete=django.db.models.deletion.CASCADE, related_name='trade_two', to='blog.trade'),
        ),
    ]
