# Generated by Django 3.1.7 on 2021-03-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210315_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name_platform',
            field=models.TextField(default='<django.db.models.fields.TextField>(<django.db.models.fields.CharField>)', max_length=240),
        ),
    ]
