# Generated by Django 3.1.7 on 2021-03-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_game_name_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name_and_platform',
            field=models.TextField(default='<django.db.models.fields.TextField>(<django.db.models.fields.CharField>)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(max_length=160),
        ),
    ]
