# Generated by Django 3.1.7 on 2021-05-02 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210430_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confirmed_to_completed_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 18, 53, 1, 567581)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='open_expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 18, 53, 1, 567599)),
        ),
    ]
