# Generated by Django 3.1.7 on 2021-03-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210317_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name_and_platform',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
