# Generated by Django 3.1.7 on 2021-05-07 05:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210506_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='desired_game',
            field=models.ForeignKey(blank=True, db_column='desired_game', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_game', to='blog.game'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='owned_game',
            field=models.ForeignKey(blank=True, db_column='owned_game', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_game', to='blog.game'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 22, 33, 16, 868270)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='open_expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 22, 33, 16, 868287)),
        ),
    ]
