# Generated by Django 3.1.7 on 2021-05-07 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20210506_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='transaction_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 9, 46, 28, 806614)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='open_expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 9, 46, 28, 806632)),
        ),
    ]
