# Generated by Django 3.1.7 on 2021-05-20 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210507_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name_and_platform',
            field=models.TextField(default='N/A', unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 17, 56, 23, 952757)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='open_expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 17, 56, 23, 952779)),
        ),
    ]
